import mongoose from 'mongoose';

import DataPlans from './models/DataPlans.js';

const gloDataPlans = [
  {
    data_id: 7,
    network: 'MTN',
    planType: 'SME',
    amount: 257,
    size: '1.0 GB',
    validity: '30 days',
  },
  {
    data_id: 8,
    network: 'MTN',
    planType: 'SME',
    amount: 514,
    size: '2.0 GB',
    validity: '30 days',
  },
  {
    data_id: 43,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 2820,
    size: '10.0 GB',
    validity: '30 days',
  },
  {
    data_id: 44,
    network: 'MTN',
    planType: 'SME',
    amount: 771,
    size: '3.0 GB',
    validity: '30 days',
  },
  {
    data_id: 49,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 72,
    size: '250.0 MB',
    validity: '30 days',
  },
  {
    data_id: 208,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 282,
    size: '1.0 GB',
    validity: '30 days',
  },
  {
    data_id: 209,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 564,
    size: '2.0 GB',
    validity: '30 days',
  },
  {
    data_id: 210,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 846,
    size: '3.0 GB',
    validity: '30 days',
  },
  {
    data_id: 211,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 1410,
    size: '5.0 GB',
    validity: '30 days',
  },
  {
    data_id: 212,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 141,
    size: '500.0 MB',
    validity: '30 days',
  },
  {
    data_id: 213,
    network: 'MTN',
    planType: 'SME',
    amount: 2570,
    size: '10.0 GB',
    validity: '30 days',
  },
  {
    data_id: 214,
    network: 'MTN',
    planType: 'SME',
    amount: 128.5,
    size: '500.0 MB',
    validity: '30 days',
  },
  {
    data_id: 215,
    network: 'MTN',
    planType: 'GIFTING',
    amount: 199,
    size: '1.0 GB',
    validity: '1 day',
  },
  {
    data_id: 216,
    network: 'MTN',
    planType: 'GIFTING',
    amount: 499,
    size: '3.5 GB',
    validity: '2 days',
  },
  {
    data_id: 217,
    network: 'MTN',
    planType: 'GIFTING',
    amount: 1999,
    size: '15.0 GB',
    validity: '7 days',
  },
  {
    data_id: 222,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 5640,
    size: '20.0 GB',
    validity: '30 days',
  },
  {
    data_id: 223,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 4230,
    size: '15.0 GB',
    validity: '30 days',
  },
  {
    data_id: 231,
    network: 'MTN',
    planType: 'SME2',
    amount: 278,
    size: '1.0 GB',
    validity: '30 days',
  },
  {
    data_id: 233,
    network: 'MTN',
    planType: 'SME2',
    amount: 556,
    size: '2.0 GB',
    validity: '30 days',
  },
  {
    data_id: 234,
    network: 'MTN',
    planType: 'SME2',
    amount: 834,
    size: '3.0 GB',
    validity: '30 days',
  },
  {
    data_id: 235,
    network: 'MTN',
    planType: 'SME2',
    amount: 1390,
    size: '5.0 GB',
    validity: '30 days',
  },
  {
    data_id: 236,
    network: 'MTN',
    planType: 'SME2',
    amount: 2780,
    size: '10.0 GB',
    validity: '30 days',
  },
  {
    data_id: 237,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 10880,
    size: '40.0 GB',
    validity: '30 days',
  },
  {
    data_id: 253,
    network: 'MTN',
    planType: 'DATA COUPONS',
    amount: 486,
    size: '2.0 GB',
    validity: 'Monthly',
  },
  {
    data_id: 254,
    network: 'MTN',
    planType: 'DATA COUPONS',
    amount: 243,
    size: '1.0 GB',
    validity: 'Monthly',
  },
  {
    data_id: 256,
    network: 'MTN',
    planType: 'DATA COUPONS',
    amount: 1215,
    size: '5.0 GB',
    validity: '30 days',
  },
  {
    data_id: 257,
    network: 'MTN',
    planType: 'DATA COUPONS',
    amount: 729,
    size: '3.0 GB',
    validity: '30 days',
  },
  {
    data_id: 259,
    network: 'MTN',
    planType: 'SME2',
    amount: 139,
    size: '500.0 MB',
    validity: '30 days',
  },
  {
    data_id: 260,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 50,
    size: '150.0 MB',
    validity: '30 days',
  },
  {
    data_id: 266,
    network: 'MTN',
    planType: 'SME2',
    amount: 408,
    size: '1.5 GB',
    validity: '30 days',
  },
  {
    data_id: 269,
    network: 'MTN',
    planType: 'SME2',
    amount: 1088,
    size: '4.0 GB',
    validity: '30 days',
  },
  {
    data_id: 270,
    network: 'MTN',
    planType: 'SME2',
    amount: 1668,
    size: '6.0 GB',
    validity: '30 days',
  },
  {
    data_id: 271,
    network: 'MTN',
    planType: 'SME2',
    amount: 1946,
    size: '7.0 GB',
    validity: '30 days',
  },
  {
    data_id: 272,
    network: 'MTN',
    planType: 'SME2',
    amount: 9430,
    size: '35.0 GB',
    validity: '30 days',
  },
  {
    data_id: 273,
    network: 'MTN',
    planType: 'SME2',
    amount: 11120,
    size: '40.0 GB',
    validity: '30 days',
  },
  {
    data_id: 274,
    network: 'MTN',
    planType: 'DATA COUPONS',
    amount: 121.5,
    size: '500.0 MB',
    validity: 'Monthly',
  },
  {
    data_id: 291,
    network: 'MTN',
    planType: 'SME',
    amount: 1285,
    size: '5.0 GB',
    validity: '30 days',
  },
  {
    data_id: 292,
    network: 'MTN',
    planType: 'CORPORATE GIFTING',
    amount: 18,
    size: '50.0 MB',
    validity: '30 days',
  },
];

const seedDatabase = async () => {
  try {
    // await DataPlans.deleteMany(); // Clears previous records
    await DataPlans.insertMany(gloDataPlans);

    console.log('data plans seeded successfully!');
    mongoose.connection.close();
  } catch (error) {
    console.error('Error seeding data plans', error);
    mongoose.connection.close();
  }
};

export default seedDatabase;
